// Mock data for CC Order Center Line OA Activities

const activities = [
  {
    id: 'act-001',
    name: 'แคมเปญซื้อครบ 4 ขั้นตอน รับคะแนนพิเศษ',
    description: 'ร่วมกิจกรรมซื้อสินค้าครบตามเป้าหมายในแต่ละขั้นตอน รับคะแนนสะสมพิเศษสูงสุด 1,000 คะแนน เพื่อแลกรับของรางวัลสุดคุ้ม!',
    status: 'joined',
    shopCode: 'CC-BKK-0042',
    dateRange: '01 มี.ค. - 31 มี.ค. 2567',
    currentStep: 2,
    totalSteps: 4,
    currentScore: 250,
    participants: 1284,
    bannerColor: '#F26522',
    bannerColorEnd: '#FF8C42',
    steps: [
      {
        id: 'step-001-1',
        title: 'ขั้นที่ 1: ซื้อสินค้าครบ 1,000 บาท',
        description: 'ซื้อสินค้าจากแคตาล็อกที่ร่วมรายการให้ครบ 1,000 บาทในช่วงระยะเวลาที่กำหนด และอัปโหลดใบเสร็จรับเงินเป็นหลักฐาน',
        dateRange: '01 มี.ค. - 10 มี.ค. 2567',
        locked: false,
        completed: true,
        evidenceUrl: null,
      },
      {
        id: 'step-001-2',
        title: 'ขั้นที่ 2: ซื้อสินค้าครบ 2,500 บาท',
        description: 'ซื้อสินค้าเพิ่มเติมให้ยอดรวมครบ 2,500 บาท แล้วอัปโหลดใบเสร็จใหม่ในช่วงเวลาที่กำหนด',
        dateRange: '11 มี.ค. - 20 มี.ค. 2567',
        locked: false,
        completed: false,
        evidenceUrl: null,
      },
      {
        id: 'step-001-3',
        title: 'ขั้นที่ 3: ซื้อสินค้าครบ 5,000 บาท',
        description: 'ยอดซื้อรวมต้องครบ 5,000 บาท ถ่ายภาพใบเสร็จทุกใบรวมกันเป็นหลักฐาน',
        dateRange: '21 มี.ค. - 28 มี.ค. 2567',
        locked: true,
        completed: false,
        evidenceUrl: null,
      },
      {
        id: 'step-001-4',
        title: 'ขั้นที่ 4: ซื้อสินค้าครบ 10,000 บาท',
        description: 'ขั้นตอนสุดท้าย! ยอดซื้อรวมครบ 10,000 บาท รับคะแนนพิเศษสูงสุด 1,000 คะแนนทันที',
        dateRange: '29 มี.ค. - 31 มี.ค. 2567',
        locked: true,
        completed: false,
        evidenceUrl: null,
      },
    ],
  },
  {
    id: 'act-002',
    name: 'กิจกรรมโปรโมชั่นสินค้าใหม่ เดือนเมษายน',
    description: 'ร่วมสนุกกับกิจกรรมพิเศษสำหรับสินค้าใหม่ประจำเดือนเมษายน! ซื้อสินค้าตามเงื่อนไข รับคะแนนสะสมและสิทธิ์แลกของรางวัลสุดพิเศษ',
    status: 'not-joined',
    shopCode: 'CC-BKK-0042',
    dateRange: '01 เม.ย. - 30 เม.ย. 2567',
    currentStep: 0,
    totalSteps: 4,
    currentScore: 0,
    participants: 856,
    bannerColor: '#00AEEF',
    bannerColorEnd: '#0066CC',
    steps: [
      {
        id: 'step-002-1',
        title: 'ขั้นที่ 1: ลงทะเบียนร่วมกิจกรรม',
        description: 'กดเข้าร่วมกิจกรรมและซื้อสินค้าใหม่อย่างน้อย 1 รายการมูลค่าไม่ต่ำกว่า 500 บาท',
        dateRange: '01 เม.ย. - 07 เม.ย. 2567',
        locked: false,
        completed: false,
        evidenceUrl: null,
      },
      {
        id: 'step-002-2',
        title: 'ขั้นที่ 2: ซื้อสินค้าครบ 2,000 บาท',
        description: 'ซื้อสินค้าจากคอลเล็กชั่นใหม่ให้ครบ 2,000 บาทภายในสัปดาห์ที่ 2 ของเดือน',
        dateRange: '08 เม.ย. - 15 เม.ย. 2567',
        locked: true,
        completed: false,
        evidenceUrl: null,
      },
      {
        id: 'step-002-3',
        title: 'ขั้นที่ 3: แนะนำสินค้าให้ลูกค้า',
        description: 'แนะนำสินค้าใหม่ให้ลูกค้าอย่างน้อย 3 ราย และอัปโหลดรูปถ่ายการนำเสนอสินค้า',
        dateRange: '16 เม.ย. - 23 เม.ย. 2567',
        locked: true,
        completed: false,
        evidenceUrl: null,
      },
      {
        id: 'step-002-4',
        title: 'ขั้นที่ 4: ยอดขายรวมครบ 8,000 บาท',
        description: 'ปิดกิจกรรมด้วยยอดขายสินค้าใหม่รวมครบ 8,000 บาท รับรางวัลพิเศษและคะแนนโบนัส',
        dateRange: '24 เม.ย. - 30 เม.ย. 2567',
        locked: true,
        completed: false,
        evidenceUrl: null,
      },
    ],
  },
  {
    id: 'act-003',
    name: 'แคมเปญปีใหม่ไทย สงกรานต์ มหาสนุก',
    description: 'กิจกรรมพิเศษช่วงสงกรานต์ที่ผ่านมา ขอบคุณทุกท่านที่ร่วมสนุกและสร้างยอดขายสุดปัง! ดูสรุปผลการร่วมกิจกรรมของคุณได้เลย',
    status: 'ended',
    shopCode: 'CC-BKK-0042',
    dateRange: '01 เม.ย. - 15 เม.ย. 2567',
    currentStep: 3,
    totalSteps: 4,
    currentScore: 750,
    participants: 2341,
    bannerColor: '#28A745',
    bannerColorEnd: '#1E7E34',
    steps: [
      {
        id: 'step-003-1',
        title: 'ขั้นที่ 1: ซื้อสินค้าครบ 1,500 บาท',
        description: 'ซื้อสินค้าที่ร่วมรายการครบ 1,500 บาท ผ่านการตรวจสอบเรียบร้อยแล้ว',
        dateRange: '01 เม.ย. - 05 เม.ย. 2567',
        locked: false,
        completed: true,
        evidenceUrl: null,
      },
      {
        id: 'step-003-2',
        title: 'ขั้นที่ 2: ซื้อสินค้าครบ 3,000 บาท',
        description: 'ยอดซื้อสะสมครบ 3,000 บาท ผ่านการตรวจสอบเรียบร้อยแล้ว',
        dateRange: '06 เม.ย. - 10 เม.ย. 2567',
        locked: false,
        completed: true,
        evidenceUrl: null,
      },
      {
        id: 'step-003-3',
        title: 'ขั้นที่ 3: ซื้อสินค้าครบ 6,000 บาท',
        description: 'ยอดซื้อสะสมครบ 6,000 บาท ผ่านการตรวจสอบเรียบร้อยแล้ว',
        dateRange: '11 เม.ย. - 13 เม.ย. 2567',
        locked: false,
        completed: true,
        evidenceUrl: null,
      },
      {
        id: 'step-003-4',
        title: 'ขั้นที่ 4: ซื้อสินค้าครบ 12,000 บาท',
        description: 'หมดเวลากิจกรรมก่อนถึงขั้นตอนสุดท้าย ติดตามกิจกรรมใหม่ๆ ได้เร็วๆ นี้',
        dateRange: '14 เม.ย. - 15 เม.ย. 2567',
        locked: true,
        completed: false,
        evidenceUrl: null,
      },
    ],
  },
];

module.exports = { activities };
